### ISSUE TITLE
Assymetric Shapley Values

### ISSUE THREAD

**Issue by OlexiyPukhov** [mayer79/kernelshap#45]
Does this also work for the calculation of asymmetric shapley values, that allow their calculation by incorporating causal information with domain knowledge? The github for a package implementing asymmetric shapley values is here:

https://github.com/nredell/shapFlex

This is made by using what the researchers have found in this paper:

https://proceedings.neurips.cc/paper/2020/file/0d770c496aa3da6d2c3f2bd19e7b9d6b-Paper.pdf

There is also a talk by the researchers explaining the theory on youtube:

https://www.youtube.com/watch?app=desktop&v=7d13f4UaAn0

**Comment by mayer79** [comment]
Thanks for sharing the material. It might indeed be interesting in certain situations. In R, there is also the "shapr" package, that implements KernelSHAP with conditional expectations. Standard KernelSHAP uses marginal expectations, which is favourable from causal inference perspective. The material above adds additional logic.

The aim of the "kernelshap" package is to provide a comparably fast implementation of the standard KernelSHAP, so at the moment, asymmetric Shapley values would be out-of-scope. One of the advantages of standard KernelSHAP is that it works for any model and any data structure. A covariate can be categorical etc. and it still runs, very unlike other approaches.
